name: EKS Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker meta  
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
           698564276851.dkr.ecr.us-east-1.amazonaws.com/user-service:latest
           698564276851.dkr.ecr.us-east-1.amazonaws.com/ticket-service:latest
           698564276851.dkr.ecr.us-east-1.amazonaws.com/helpdesk-service:latest

      - name: Configurar AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Configurar Docker para autenticação ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 698564276851.dkr.ecr.us-east-1.amazonaws.com
          
      - name: Build and Push Docker Images
        run: |
          docker build -t ${{ secrets.AWS_ACCESS_KEY_ID }}.dkr.ecr.${{ secrets.AWS_SECRET_ACCESS_KEY }}.amazonaws.com/user-service:latest ./user-service
          docker build -t ${{ secrets.AWS_ACCESS_KEY_ID }}.dkr.ecr.${{ secrets.AWS_SECRET_ACCESS_KEY }}.amazonaws.com/ticket-service:latest ./ticket-service
          docker build -t ${{ secrets.AWS_ACCESS_KEY_ID }}.dkr.ecr.${{ secrets.AWS_SECRET_ACCESS_KEY }}.amazonaws.com/helpdesk-service:latest ./helpdesk-service
  
          docker push 698564276851.dkr.ecr.us-east-1.amazonaws.com/user-service:latest
          docker push 698564276851.dkr.ecr.us-east-1.amazonaws.com/ticket-service:latest
          docker push 698564276851.dkr.ecr.us-east-1.amazonaws.com/helpdesk-service:latest

      - name: Deploy to EKS
        run: |
          kubectl apply -f ./user-service/kubernetes
          kubectl apply -f ./ticket-service/kubernetes
          kubectl apply -f ./helpdesk-service/kubernetes